[2024-04-16T08:51:21.248+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: spotify_final_dag.hello scheduled__2024-04-16T02:30:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
