[2024-04-16T09:45:41.902+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-16T09:45:41.935+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_final_dag.hello2 scheduled__2024-04-16T00:22:00+00:00 [queued]>
[2024-04-16T09:45:41.947+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_final_dag.hello2 scheduled__2024-04-16T00:22:00+00:00 [queued]>
[2024-04-16T09:45:41.948+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-04-16T09:45:41.970+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): hello2> on 2024-04-16 00:22:00+00:00
[2024-04-16T09:45:41.978+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3703) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-16T09:45:41.981+0000] {standard_task_runner.py:63} INFO - Started process 3733 to run task
[2024-04-16T09:45:41.981+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spotify_final_dag', 'hello2', 'scheduled__2024-04-16T00:22:00+00:00', '--job-id', '942', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp1ekxxwy0']
[2024-04-16T09:45:41.982+0000] {standard_task_runner.py:91} INFO - Job 942: Subtask hello2
[2024-04-16T09:45:42.057+0000] {task_command.py:426} INFO - Running <TaskInstance: spotify_final_dag.hello2 scheduled__2024-04-16T00:22:00+00:00 [running]> on host 52651c1f9987
[2024-04-16T09:45:42.135+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_final_dag' AIRFLOW_CTX_TASK_ID='hello2' AIRFLOW_CTX_EXECUTION_DATE='2024-04-16T00:22:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-16T00:22:00+00:00'
[2024-04-16T09:45:42.136+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-16T09:45:45.704+0000] {logging_mixin.py:188} INFO - There was a problem with the connection. Trial number 1, Status Code: 401
[2024-04-16T09:45:48.993+0000] {logging_mixin.py:188} INFO - There was a problem with the connection. Trial number 2, Status Code: 401
[2024-04-16T09:45:48.996+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-16T09:45:48.998+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/get_data.py", line 95, in processes
    album_data = get_album(connection())
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/get_data.py", line 11, in get_album
    for album in data["items"]:
                 ~~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-04-16T09:45:49.011+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=spotify_final_dag, task_id=hello2, execution_date=20240416T002200, start_date=20240416T094541, end_date=20240416T094549
[2024-04-16T09:45:49.025+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 942 for task hello2 ('NoneType' object is not subscriptable; 3733)
[2024-04-16T09:45:49.053+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-16T09:45:49.065+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-16T09:45:49.067+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
