[2024-04-17T05:21:58.286+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-17T05:21:58.313+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_final_dag.hello2 scheduled__2024-04-16T10:38:00+00:00 [queued]>
[2024-04-17T05:21:58.325+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_final_dag.hello2 scheduled__2024-04-16T10:38:00+00:00 [queued]>
[2024-04-17T05:21:58.326+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-04-17T05:21:58.343+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): hello2> on 2024-04-16 10:38:00+00:00
[2024-04-17T05:21:58.353+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=180) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-17T05:21:58.354+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spotify_final_dag', 'hello2', 'scheduled__2024-04-16T10:38:00+00:00', '--job-id', '1602', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp2rdo33m3']
[2024-04-17T05:21:58.355+0000] {standard_task_runner.py:63} INFO - Started process 208 to run task
[2024-04-17T05:21:58.355+0000] {standard_task_runner.py:91} INFO - Job 1602: Subtask hello2
[2024-04-17T05:21:58.415+0000] {task_command.py:426} INFO - Running <TaskInstance: spotify_final_dag.hello2 scheduled__2024-04-16T10:38:00+00:00 [running]> on host 52651c1f9987
[2024-04-17T05:21:58.522+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_final_dag' AIRFLOW_CTX_TASK_ID='hello2' AIRFLOW_CTX_EXECUTION_DATE='2024-04-16T10:38:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-16T10:38:00+00:00'
[2024-04-17T05:21:58.524+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-17T05:22:02.083+0000] {logging_mixin.py:188} INFO - There was a problem with the connection. Trial number 1, Status Code: 401
[2024-04-17T05:22:05.343+0000] {logging_mixin.py:188} INFO - There was a problem with the connection. Trial number 2, Status Code: 401
[2024-04-17T05:22:05.346+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-17T05:22:05.348+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/get_data.py", line 95, in processes
    album_data = get_album(connection())
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/get_data.py", line 11, in get_album
    for album in data["items"]:
                 ~~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-04-17T05:22:05.357+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=spotify_final_dag, task_id=hello2, execution_date=20240416T103800, start_date=20240417T052158, end_date=20240417T052205
[2024-04-17T05:22:05.369+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1602 for task hello2 ('NoneType' object is not subscriptable; 208)
[2024-04-17T05:22:05.386+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-17T05:22:05.403+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-17T05:22:05.406+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
