[2024-04-17T05:21:59.749+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-17T05:21:59.767+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_final_dag.hello2 scheduled__2024-04-16T10:24:00+00:00 [queued]>
[2024-04-17T05:21:59.774+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_final_dag.hello2 scheduled__2024-04-16T10:24:00+00:00 [queued]>
[2024-04-17T05:21:59.775+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-04-17T05:21:59.790+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): hello2> on 2024-04-16 10:24:00+00:00
[2024-04-17T05:21:59.801+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=178) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-17T05:21:59.802+0000] {standard_task_runner.py:63} INFO - Started process 217 to run task
[2024-04-17T05:21:59.802+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spotify_final_dag', 'hello2', 'scheduled__2024-04-16T10:24:00+00:00', '--job-id', '1611', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpm3dogtfh']
[2024-04-17T05:21:59.804+0000] {standard_task_runner.py:91} INFO - Job 1611: Subtask hello2
[2024-04-17T05:21:59.845+0000] {task_command.py:426} INFO - Running <TaskInstance: spotify_final_dag.hello2 scheduled__2024-04-16T10:24:00+00:00 [running]> on host 52651c1f9987
[2024-04-17T05:21:59.923+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_final_dag' AIRFLOW_CTX_TASK_ID='hello2' AIRFLOW_CTX_EXECUTION_DATE='2024-04-16T10:24:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-16T10:24:00+00:00'
[2024-04-17T05:21:59.924+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-17T05:22:03.493+0000] {logging_mixin.py:188} INFO - There was a problem with the connection. Trial number 1, Status Code: 401
[2024-04-17T05:22:06.772+0000] {logging_mixin.py:188} INFO - There was a problem with the connection. Trial number 2, Status Code: 401
[2024-04-17T05:22:06.774+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-17T05:22:06.775+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/get_data.py", line 95, in processes
    album_data = get_album(connection())
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/get_data.py", line 11, in get_album
    for album in data["items"]:
                 ~~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-04-17T05:22:06.784+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=spotify_final_dag, task_id=hello2, execution_date=20240416T102400, start_date=20240417T052159, end_date=20240417T052206
[2024-04-17T05:22:06.793+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1611 for task hello2 ('NoneType' object is not subscriptable; 217)
[2024-04-17T05:22:06.832+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-17T05:22:06.843+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-17T05:22:06.845+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
