[2024-04-17T07:31:01.869+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: etl_for_spotify.hello2 scheduled__2024-04-16T05:26:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
