[2024-04-17T07:28:05.529+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-17T07:28:05.553+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_for_spotify.hello2 scheduled__2024-04-16T00:10:00+00:00 [queued]>
[2024-04-17T07:28:05.564+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_for_spotify.hello2 scheduled__2024-04-16T00:10:00+00:00 [queued]>
[2024-04-17T07:28:05.565+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-17T07:28:05.579+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): hello2> on 2024-04-16 00:10:00+00:00
[2024-04-17T07:28:05.587+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5356) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-17T07:28:05.588+0000] {standard_task_runner.py:63} INFO - Started process 5378 to run task
[2024-04-17T07:28:05.588+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_for_spotify', 'hello2', 'scheduled__2024-04-16T00:10:00+00:00', '--job-id', '2771', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpstd4a3u6']
[2024-04-17T07:28:05.590+0000] {standard_task_runner.py:91} INFO - Job 2771: Subtask hello2
[2024-04-17T07:28:05.641+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_for_spotify.hello2 scheduled__2024-04-16T00:10:00+00:00 [running]> on host 52651c1f9987
[2024-04-17T07:28:05.742+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_for_spotify' AIRFLOW_CTX_TASK_ID='hello2' AIRFLOW_CTX_EXECUTION_DATE='2024-04-16T00:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-16T00:10:00+00:00'
[2024-04-17T07:28:05.743+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-17T07:28:09.300+0000] {logging_mixin.py:188} INFO - There was a problem with the connection. Trial number 1, Status Code: 401
[2024-04-17T07:28:12.572+0000] {logging_mixin.py:188} INFO - There was a problem with the connection. Trial number 2, Status Code: 401
[2024-04-17T07:28:12.574+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-17T07:28:12.575+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/get_data.py", line 94, in processes
    album_data = get_album(connection())
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/get_data.py", line 10, in get_album
    for album in data["items"]:
                 ~~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-04-17T07:28:12.585+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_for_spotify, task_id=hello2, execution_date=20240416T001000, start_date=20240417T072805, end_date=20240417T072812
[2024-04-17T07:28:12.596+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2771 for task hello2 ('NoneType' object is not subscriptable; 5378)
[2024-04-17T07:28:12.628+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-17T07:28:12.645+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-17T07:28:12.648+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
